# Generated by Django 2.1.3 on 2018-11-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='seen',
        ),
    ]
